init.d: usbgadget: Warn early if no UDC found
Summary:
If there are no USB Device Controller (UDC) then the diretory
`/sys/class/udc/` is empty and the command:
    ls /sys/class/udc/ | head -n1 > UDC
will not enable the usb gadget on the first available controller,
but it will silently disable the gadget (by writing en empty string).

Add a test early in script that will warn and exit with error if there
are no UDC found.

ref T19685

Test Plan: CI

Reviewers: O53 Buildroot Coolidge!

Subscribers: #linux_coolidge_cc

Differential Revision: https://phab.kalray.eu/D22182

diff --git a/board/kalray/common/rootfs_overlay/etc/init.d/S30usbgadget b/board/kalray/common/rootfs_overlay/etc/init.d/S30usbgadget
--- a/board/kalray/common/rootfs_overlay/etc/init.d/S30usbgadget
+++ b/board/kalray/common/rootfs_overlay/etc/init.d/S30usbgadget
@@ -5,7 +5,14 @@ umask 077
 CONFIGFS_HOME=/sys/kernel/config
 
 start() {
+	# grab the first UDC device found
+	udc="$(ls /sys/class/udc/ | head -n1)"
 	printf "Starting usb gadget: "
+	if [ -z "$udc" ]; then
+		echo "FAIL: no available controller"
+		exit 1
+	fi
+
 	modprobe libcomposite
 	modprobe usb_f_acm
 	modprobe usb_f_ecm
@@ -37,8 +44,8 @@ start() {
 	ln -fs functions/ecm.usb0 configs/c.1
 	ln -fs functions/acm.GS0 configs/c.1
 
-	# enable the usb gadget on the first UDC device found
-	ls /sys/class/udc/ | head -n1 > UDC
+	# enable the usb gadget
+	printf "$udc" > UDC
 
 	echo "OK"
 }
