Move package coolval in common configuration
Summary:
As coolval is now run on HW and on ISS we moved the package in common.
We also modified the initscript to run test only on ISS. We just keep
the configuration of huge pages for both (HW and ISS) but after
configuration is done we just exit if it executes on HW.

Test Plan: Check in integration that coolval is run on HW and on ISS

Reviewers: O53 Buildroot Coolidge!

Subscribers: #linux_coolidge_cc

Differential Revision: https://phab.kalray.eu/D2042

diff --git a/package/kalray/coolval/S30coolval b/package/kalray/coolval/S30coolval
--- a/package/kalray/coolval/S30coolval
+++ b/package/kalray/coolval/S30coolval
@@ -1,60 +1,34 @@
 #!/bin/sh
 #
-# Start the coolidge k1c validation binary
-#
+# Start the coolidge k1c validation binary on ISS
 
-# mount debugfs and activate pr_debug for kernel/module.c
-# This is needed to get memory layout of module
-# So that check_vmlinux.sh is able to validate kernel module relocs
-mount -t debugfs none /sys/kernel/debug/
-echo 'file kernel/module.c +p' > /sys/kernel/debug/dynamic_debug/control
-modprobe module_tests
-echo 'file kernel/module.c -p' > /sys/kernel/debug/dynamic_debug/control
+# Coolval on HW is started from Robotframework. So this init script is only
+# needed to run coolval on ISS.
+DTMODEL="/sys/firmware/devicetree/base/model"
+grep -q ISS "$DTMODEL" 2>/dev/null || exit 0 # Only run coolval on ISS
 
-# Load ext2+loop and create/mount a small ext2 file system
-# in order to exercise kernel modules a bit more.
-modprobe ext2
-modprobe loop
-dd if=/dev/zero of=ext2.raw bs=1M count=1
-losetup /dev/loop0 ext2.raw
-mkfs.ext2 /dev/loop0
-mkdir /extmnt /extmnt2
-mount -o loop -t ext2 ext2.raw /extmnt
-echo "EXT2 TEST: OK" > /extmnt/msg
-umount /extmnt
-mount -o loop -t ext2 ext2.raw /extmnt2
-cat /extmnt2/msg
-umount /extmnt2
-rm -rf /extmnt /extmnt2 ext2.raw
+set -ex
 
-# Before launching coolval we need to enable hugepage. The test will map, write
-# and read 10Mo. So we let's allocate 5 huge pages of 2Mo
-
-echo 5 > /proc/sys/vm/nr_hugepages
-mkdir -p /mnt/huge_2mb
-mount -t hugetlbfs nodev /mnt/huge_2mb
-
-# and 160 pages of 64Ko
-echo 160 > /sys/kernel/mm/hugepages/hugepages-64kB/nr_hugepages
-mkdir -p /mnt/huge_64kb
-mount -t hugetlbfs nodev /mnt/huge_64kb -o pagesize=64K
-
-modprobe k1c_dma_noc_test
-modprobe -r k1c_dma_noc_test
-
-# OK we are now ready to launch coolval tests. Exit directly if a coolval test
-# returns a non-zero value.
-set -e
+COOLVALDIR="/opt/coolval"
 
 run_coolval_tests() {
-	for testname in "$@"; do
-		echo ">>>>> $testname begin"
-		/bin/coolval -t "$testname"
-		echo ">>>>> $testname succeeded"
+	for TESTNAME in "$@"; do
+		echo ">>>>> $TESTNAME begin"
+		"$COOLVALDIR"/run_tests -t "$TESTNAME"
+		echo ">>>>> $TESTNAME succeeded"
 		echo
 	done
 }
 
+# Test modules
+"$COOLVALDIR"/test_modules.sh
+
+# Init huge pages for coolval
+"$COOLVALDIR"/init_hugepages.sh
+
 run_coolval_tests 'dtouchl' 'fork' 'fpu' 'hugemap' 'jmp' \
 		  'jump_reg_saving' 'malloc' 'signal' 'syscall' \
 		  'ttyKS0' 'wchar' 'stackprotector'
+
+# Cleanup goes here
+"$COOLVALDIR"/clear_hugepages.sh
